### ISSUE TITLE
Save configuration files on MongoDB instead of locally

### ISSUE THREAD

**Issue by empicano** [fast-survey/backend#32]

**Comment by dostuffthatmatters** [comment]
Which version do you prefer:

1) A separate database on our db cluster that has a public access for reading, so that our frontend (anyone) can directly access this particular collection. Only for the survey config files!

2) No public key but a backend endpoint to fetch the survey config files (from the db or from the instantiated models)

*Personally I prefer the first method, but you definitely have a better overview over the v0.3+ backend.*

**Comment by empicano** [comment]
Using the first method would prevent us to be able to redact certain information from the configuration files before sending them to the frontend e.g. contact email address (used during mailing as reply to address). We could save this specific information in a separate collection though, too e.g. in separate email configuration documents. Furthermore, direct access to the configuration collection would enable anyone to quickly make a complete map of every existing survey. I'm not sure how desirable that is (With option two, one would need to submit the username and survey id to access the configuration).

Apart from that, if my comment about connection counts in #31 holds true, this would be unfeasable due to every website visitor needing to open a new connection to the database.

What would be reasons to go with option one, performance probably, did you have anything else in mind?

**Comment by dostuffthatmatters** [comment]
My point was actually to improve performance and kind of increase the serverless aspect.

But you have a lot of valid points and after thinking it through again. The seconds approach is definitely better 😅 

Redacting information is a great point!

And connection count too. In the end the db is not a REST endpoint but actually requires all the connection setup overhead!
